# Generated by Django 5.2.4 on 2025-07-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
