# Generated by Django 5.2.4 on 2025-07-26 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_reunion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='date_reunion',
        ),
        migrations.AddField(
            model_name='reunion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reunion',
            name='titre',
            field=models.CharField(default='Titre par défaut', max_length=200),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
